name: "CI"

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1

  unit-test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      - name: Install the project dependencies
        run: poetry install --without dev

      - name: Test with pytest
        run: |
          poetry run pytest -v test/unit 
  
  regression-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
        node-version: [20]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install node dependencies
        run: |
          mkdir test/regression/node_root
          cp test/regression/index.js test/regression/node_root
          cd test/regression/node_root
          npm init -y
          npm install oniguruma typescript vscode-oniguruma vscode-textmate

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      - name: Install the project dependencies
        run: poetry install --without dev

      - name: Test with pytest
        run: |
          poetry run pytest -v test/regression 
